# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d511faa3f0366a2f524024fef2c34571307b010d419e2c7fea13dff7dee4c7c63546a32575b436df6a337170d9b63362ef89fce1803ef5cc5140357fbc9e8e66

test:
  secret_key_base: b4ca2f09967e2921313dcd427ac067ce67e68a95483328179db40fe891cf9a1dbe8f225dcebd499807c27ea503a7d86da459db7f6072c1660cf96b1215eacecd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
